/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.infrastructure.spring.SpringContext;
import jakarta.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component //Bean gerenciado
@Scope("prototype") /*
                     *Uma nova instância é aberta toda vez que abrir a tela
                     *Impede que as telas com dados antigos
                    */
public class TelaInicial extends javax.swing.JFrame {
    
    
    @Autowired //Injeta automaticamente o Controller
    private CursoIController cursoController;
    
    private List<Curso> lista = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    
    public TelaInicial() {
    initComponents();
    }
    
    @PostConstruct //executa depois do Spring, atualizando a tela sempre
    public void init(){
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncadastrar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbltelacurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabeladecursos = new javax.swing.JTable();
        btneditarinformacao = new javax.swing.JButton();
        btndeletarinformacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastrar.png"))); // NOI18N
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, 30));

        btnlistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        jLabel2.setText("CADASTRAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        lbltelacurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltelacurso.setText("TELA CURSO");
        lbltelacurso.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lbltelacurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 30));

        tbltabeladecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbltabeladecursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 420, 220));

        btneditarinformacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btneditarinformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarinformacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btneditarinformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 50, 20));

        btndeletarinformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remover.png"))); // NOI18N
        btndeletarinformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarinformacoesActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletarinformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 140, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void atualizarTabela() {
        //modelo da tabla
        DefaultTableModel model = (DefaultTableModel) tbltabeladecursos.getModel();
        model.setRowCount(0); // limpa a tabela

        lista = cursoController.findAll(); // busca todos os cursos no BD

        //realiza a adição como uma linha
        for (Curso c : lista) {
            model.addRow(new Object[]{
                c.getId(),
                c.getCodigocurso(),
                c.getNome(),
                c.isAtivo() ? "Sim" : "Não"
            });
        }
    }
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        //Abre a tela via Spring
       TelaCadastro telaCadastro = SpringContext.getBean(TelaCadastro.class);
       telaCadastro.setTelaInicial(this);
       telaCadastro.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        TelaListar telaListar = SpringContext.getBean(TelaListar.class);
        telaListar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btneditarinformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarinformacaoActionPerformed
        // TODO add your handling code here:
        try{
        int linhaeditar = tbltabeladecursos.getSelectedRow();
        Curso dados = lista.get(linhaeditar);
        
       TelaEditar telaEditar = SpringContext.getBean(TelaEditar.class);
       telaEditar.setCurso(dados);
       telaEditar.setTelaInicial(this); 
       telaEditar.setVisible(true);
       this.dispose();
       
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Selecione uma opção para editar");
        }
    }//GEN-LAST:event_btneditarinformacaoActionPerformed

    private void btndeletarinformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarinformacoesActionPerformed
        // TODO add your handling code here:
        
        int linharemover = tbltabeladecursos.getSelectedRow();
        
        if(linharemover == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma opção para deletar");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja remover esses dados?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
            Long id = Long.valueOf(tbltabeladecursos.getValueAt(linharemover, 0).toString());
            Curso c = cursoController.findById(id);
            
            if(c == null){
                JOptionPane.showMessageDialog(this, "Curso não encontrado");
            }else{
                cursoController.delete(c);
                JOptionPane.showMessageDialog(this, "Dado removido");
                atualizarTabela();
            }
            
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Operação cancelada.");
        }
    }//GEN-LAST:event_btndeletarinformacoesActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btndeletarinformacoes;
    private javax.swing.JButton btneditarinformacao;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltelacurso;
    private javax.swing.JTable tbltabeladecursos;
    // End of variables declaration//GEN-END:variables

    
}
