/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDAO;
import br.com.ifba.curso.dao.CursoIDAO;
import br.com.ifba.curso.entity.Curso;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btncadastrar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbltelacurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltabeladecursos = new javax.swing.JTable();
        btneditarinformacao = new javax.swing.JButton();
        btndeletarinformacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btncadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\cadastrar.png")); // NOI18N
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, -1));

        btnlistar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\pesquisar.png")); // NOI18N
        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        jLabel2.setText("CADASTRAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        lbltelacurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltelacurso.setText("TELA CURSO");
        lbltelacurso.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lbltelacurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 30));

        tbltabeladecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Status"
            }
        ));
        jScrollPane1.setViewportView(tbltabeladecursos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 420, 220));

        btneditarinformacao.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\editar.png")); // NOI18N
        btneditarinformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarinformacaoActionPerformed(evt);
            }
        });
        getContentPane().add(btneditarinformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 50, 20));

        btndeletarinformacoes.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\remover.png")); // NOI18N
        btndeletarinformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletarinformacoesActionPerformed(evt);
            }
        });
        getContentPane().add(btndeletarinformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 140, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*public void atualizarTabela(){
        CursoDAO cursodao = new CursoDAO();
        List<Curso> listadecursos = cursodao.listar();
        
        DefaultTableModel model = (DefaultTableModel) tbltabeladecursos.getModel();
        
        
        for(Curso c : listadecursos){
            model.addRow(new Object[] {
                c.getCodigocurso(),
                c.getNome(),
                c.isAtivo() ? "ativo" : "inativo"
            });
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt){
        atualizarTabela();
    }*/
    
    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastro telacadastro = new TelaCadastro(this);
        telacadastro.setVisible(true);
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        TelaListar telalistar = new TelaListar();
        telalistar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btneditarinformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarinformacaoActionPerformed
        // TODO add your handling code here:
        try{
        int linhaeditar = tbltabeladecursos.getSelectedRow();
        long id = Long.parseLong(tbltabeladecursos.getValueAt(linhaeditar, 0).toString());
        String codigocurso = tbltabeladecursos.getValueAt(linhaeditar, 1).toString();
        String nome = tbltabeladecursos.getValueAt(linhaeditar, 2).toString();
        boolean status = Boolean.parseBoolean(tbltabeladecursos.getValueAt(linhaeditar, 3).toString());
        
        TelaEditar telaeditar = new TelaEditar(id, codigocurso, nome, status);
        telaeditar.setVisible(true);
        atualizarTabela();
        this.dispose();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Selecione uma opção para editar");
        }
    }//GEN-LAST:event_btneditarinformacaoActionPerformed

    private void btndeletarinformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletarinformacoesActionPerformed
        // TODO add your handling code here:
        
        int linharemover = tbltabeladecursos.getSelectedRow();
        
        if(linharemover == -1){
            JOptionPane.showMessageDialog(this, "Selecione uma opção para deletar");
            return;
        }
        
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja remover esses dados?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(resposta == JOptionPane.YES_OPTION){
            try{
            Long id = Long.valueOf(tbltabeladecursos.getValueAt(linharemover, 0).toString());
            CursoIDAO cursodao = new CursoDAO();
            Curso c = cursodao.buscarPorId(id);
            
            if(c != null){
                cursodao.remover(c);
                JOptionPane.showMessageDialog(this, "Dado removido");
                atualizarTabela();
            }else{
                JOptionPane.showMessageDialog(this, "Curso não encontrado");
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Erro ao remover: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Operação cancelada.");
        }
    }//GEN-LAST:event_btndeletarinformacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btndeletarinformacoes;
    private javax.swing.JButton btneditarinformacao;
    private javax.swing.JButton btnlistar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltelacurso;
    private javax.swing.JTable tbltabeladecursos;
    // End of variables declaration//GEN-END:variables

    public void atualizarTabela() {
        DefaultTableModel model = (DefaultTableModel) tbltabeladecursos.getModel();
        model.setRowCount(0); // limpa a tabela

    CursoDAO dao = new CursoDAO();
    List<Curso> lista = dao.listarcursos(); // busca todos os cursos no BD

    for (Curso c : lista) {
        model.addRow(new Object[]{
            c.getId(),
            c.getCodigocurso(),
            c.getNome(),
            c.isAtivo() ? "Sim" : "Não"
        });
    }
    }
}
