/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcadastrarnome = new javax.swing.JLabel();
        txtcadastrarnome = new javax.swing.JTextField();
        btnsalvarcadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcadastrarnome.setText("NOME:");
        getContentPane().add(lblcadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 62, -1, -1));
        getContentPane().add(txtcadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 150, -1));

        btnsalvarcadastro.setText("SALVAR");
        btnsalvarcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarcadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvarcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarcadastroActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Cadastro Salvo!");
        TelaInicial telainicial = new TelaInicial();
        telainicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsalvarcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvarcadastro;
    private javax.swing.JLabel lblcadastrarnome;
    private javax.swing.JTextField txtcadastrarnome;
    // End of variables declaration//GEN-END:variables
}
