/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.infrastructure.spring.SpringContext;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author USER
 */

@Component
@Scope("prototype")
public class TelaEditar extends javax.swing.JFrame {
    
    
    @Autowired
    private CursoIController cursoController;
    
    private TelaInicial telainicial;
    private Curso curso; 
    
    public void setTelaInicial(TelaInicial telainicial) {
        this.telainicial = telainicial;
    }

    public void setCurso(Curso curso) {
        this.curso = curso;
        txteditarnome.setText(curso.getNome());
        txtcodigocursoeditar.setText(curso.getCodigocurso());
    }

    public TelaEditar() {
        initComponents();
    }
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditar.class.getName());

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbleditarnome = new javax.swing.JLabel();
        txteditarnome = new javax.swing.JTextField();
        btnsalvaredicao = new javax.swing.JButton();
        lblcodigocursoeditar = new javax.swing.JLabel();
        txtcodigocursoeditar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbleditarnome.setText("Nome");
        getContentPane().add(lbleditarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txteditarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditarnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txteditarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 280, -1));

        btnsalvaredicao.setText("SALVAR");
        btnsalvaredicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvaredicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvaredicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblcodigocursoeditar.setText("CÓDIGO");
        getContentPane().add(lblcodigocursoeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        getContentPane().add(txtcodigocursoeditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txteditarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditarnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteditarnomeActionPerformed

    private void btnsalvaredicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvaredicaoActionPerformed
        // TODO add your handling code here:
        try{
            curso.setCodigocurso(txtcodigocursoeditar.getText());
            curso.setNome(txteditarnome.getText());
            
            cursoController.update(curso);
            JOptionPane.showMessageDialog(this, "Dados Alterados!");
            
            telainicial.atualizarTabela();
            telainicial.setVisible(true);
            this.dispose();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnsalvaredicaoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvaredicao;
    private javax.swing.JLabel lblcodigocursoeditar;
    private javax.swing.JLabel lbleditarnome;
    private javax.swing.JTextField txtcodigocursoeditar;
    private javax.swing.JTextField txteditarnome;
    // End of variables declaration//GEN-END:variables
}
