/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.infrastructure.util.StringUtil;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class TelaCadastro extends javax.swing.JFrame {

private final CursoIController cursoController = new CursoController();

private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastro.class.getName());
    /**
     * Creates new form TelaCadastro
     */

    // Referência à tela inicial para atualizar a tabela após o cadastro
    private TelaInicial aThis;
    
    
    public TelaCadastro(TelaInicial aThis) {
        initComponents();
        this.aThis = aThis; //Recebe uma instância de TelaInicial (para atualizar a lista ao salvar um novo curso).
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblcadastrarnome = new javax.swing.JLabel();
        txtcadastrarnome = new javax.swing.JTextField();
        btnsalvarcadastro = new javax.swing.JButton();
        btnvoltarcadastro = new javax.swing.JButton();
        lblcodigocurso = new javax.swing.JLabel();
        txtcodigocursocadastro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcadastrarnome.setText("NOME:");
        getContentPane().add(lblcadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 62, -1, -1));
        getContentPane().add(txtcadastrarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 270, -1));

        btnsalvarcadastro.setText("SALVAR");
        btnsalvarcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarcadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalvarcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        btnvoltarcadastro.setText("VOLTAR");
        btnvoltarcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarcadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltarcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        lblcodigocurso.setText("CÓDIGO");
        getContentPane().add(lblcodigocurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(txtcodigocursocadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarcadastroActionPerformed
        // TODO add your handling code here:
      
        try{
            if(StringUtil.isNullOrEmpty(txtcodigocursocadastro.getText())){
                JOptionPane.showMessageDialog(this, "O campo código é obrigatório");
                return;
            }
            if(StringUtil.isNullOrEmpty(txtcadastrarnome.getText())){
                JOptionPane.showMessageDialog(this, "O nome é obrigatório");
            }
            
        Curso curso = new Curso();
        curso.setCodigocurso(txtcodigocursocadastro.getText());
        curso.setNome(txtcadastrarnome.getText());
        curso.setAtivo(true);
        cursoController.save(curso);
        
        JOptionPane.showMessageDialog(this, "Cadastro Salvo!");
        
            if(aThis != null){
             aThis.atualizarTabela();
            }
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
       
    }//GEN-LAST:event_btnsalvarcadastroActionPerformed

    private void btnvoltarcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarcadastroActionPerformed
        // TODO add your handling code here:
        TelaInicial telainicial = new TelaInicial();
        telainicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltarcadastroActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvarcadastro;
    private javax.swing.JButton btnvoltarcadastro;
    private javax.swing.JLabel lblcadastrarnome;
    private javax.swing.JLabel lblcodigocurso;
    private javax.swing.JTextField txtcadastrarnome;
    private javax.swing.JTextField txtcodigocursocadastro;
    // End of variables declaration//GEN-END:variables
}
