/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btneditar = new javax.swing.JButton();
        btnremover = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();
        btnlistar = new javax.swing.JButton();
        lblnometelainicial = new javax.swing.JLabel();
        txtnomeinicial = new javax.swing.JTextField();
        txtnomeinial2 = new javax.swing.JTextField();
        btnremover1 = new javax.swing.JButton();
        btneditar1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblcodigotelainicial = new javax.swing.JLabel();
        txtcodigotelainicial = new javax.swing.JTextField();
        txtcodigotelainicial1 = new javax.swing.JTextField();
        lblativotelainicial = new javax.swing.JLabel();
        txtativotelainicial = new javax.swing.JTextField();
        txtativotelainicial1 = new javax.swing.JTextField();
        lbltela = new javax.swing.JLabel();
        lbltelacurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btneditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\editar.png")); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 40, 20));

        btnremover.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\remover.png")); // NOI18N
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });
        getContentPane().add(btnremover, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 40, 20));

        btncadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\cadastrar.png")); // NOI18N
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btncadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 110, -1));

        btnlistar.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\pesquisar.png")); // NOI18N
        btnlistar.setText("LISTAR");
        btnlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, -1));

        lblnometelainicial.setBackground(new java.awt.Color(204, 255, 255));
        lblnometelainicial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblnometelainicial.setText("NOME");
        getContentPane().add(lblnometelainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));
        getContentPane().add(txtnomeinicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 230, -1));
        getContentPane().add(txtnomeinial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, -1));

        btnremover1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\remover.png")); // NOI18N
        btnremover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremover1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnremover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 40, 20));

        btneditar1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USER\\Documents\\NetBeansProjects\\prg03persistencia\\src\\main\\java\\br\\com\\ifba\\curso\\view\\images\\editar.png")); // NOI18N
        btneditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btneditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 40, 20));

        jLabel2.setText("CADASTRAR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        lblcodigotelainicial.setText("CÓDIGO");
        getContentPane().add(lblcodigotelainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        getContentPane().add(txtcodigotelainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 80, -1));
        getContentPane().add(txtcodigotelainicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 80, -1));

        lblativotelainicial.setText("ATIVO");
        getContentPane().add(lblativotelainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));
        getContentPane().add(txtativotelainicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 140, 80, -1));
        getContentPane().add(txtativotelainicial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 170, 80, -1));

        lbltela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbltela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 510, 200));

        lbltelacurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltelacurso.setText("TELA CURSO");
        lbltelacurso.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(lbltelacurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        TelaEditar teladeedicao = new TelaEditar();
        teladeedicao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
        // TODO add your handling code here:
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja remover ?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);
        
        if(confirmacao == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Dados removidos");
        }else{
            JOptionPane.showMessageDialog(this, "Remoção Cancelada");
        }
    }//GEN-LAST:event_btnremoverActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        TelaCadastro telacadastro = new TelaCadastro();
        telacadastro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncadastrarActionPerformed

    private void btnlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistarActionPerformed
        // TODO add your handling code here:
        TelaListar telalistar = new TelaListar();
        telalistar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnlistarActionPerformed

    private void btnremover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremover1ActionPerformed
        // TODO add your handling code here:
        int confirmacao = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja remover ?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);
        
        if(confirmacao == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Dados removidos");
        }else{
            JOptionPane.showMessageDialog(this, "Remoção Cancelada");
        }
    }//GEN-LAST:event_btnremover1ActionPerformed

    private void btneditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditar1ActionPerformed
        // TODO add your handling code here:
        TelaEditar teladeedicao = new TelaEditar();
        teladeedicao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btneditar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneditar1;
    private javax.swing.JButton btnlistar;
    private javax.swing.JButton btnremover;
    private javax.swing.JButton btnremover1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblativotelainicial;
    private javax.swing.JLabel lblcodigotelainicial;
    private javax.swing.JLabel lblnometelainicial;
    private javax.swing.JLabel lbltela;
    private javax.swing.JLabel lbltelacurso;
    private javax.swing.JTextField txtativotelainicial;
    private javax.swing.JTextField txtativotelainicial1;
    private javax.swing.JTextField txtcodigotelainicial;
    private javax.swing.JTextField txtcodigotelainicial1;
    private javax.swing.JTextField txtnomeinial2;
    private javax.swing.JTextField txtnomeinicial;
    // End of variables declaration//GEN-END:variables
}
