/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

/**
 *
 * @author USER
 */
public class TelaEditar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEditar.class.getName());

    /**
     * Creates new form TelaEditar
     */
    public TelaEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbleditarnome = new javax.swing.JLabel();
        txteditarnome = new javax.swing.JTextField();
        btnsalvaredicao = new javax.swing.JButton();
        btnvoltardaedicao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbleditarnome.setText("Nome");
        getContentPane().add(lbleditarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 45, -1, -1));

        txteditarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteditarnomeActionPerformed(evt);
            }
        });
        getContentPane().add(txteditarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        btnsalvaredicao.setText("SALVAR");
        getContentPane().add(btnsalvaredicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        btnvoltardaedicao.setText("VOLTAR");
        btnvoltardaedicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltardaedicaoActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltardaedicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnvoltardaedicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltardaedicaoActionPerformed
        // TODO add your handling code here:
        TelaInicial telainicial = new TelaInicial();
        telainicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltardaedicaoActionPerformed

    private void txteditarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteditarnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteditarnomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEditar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalvaredicao;
    private javax.swing.JButton btnvoltardaedicao;
    private javax.swing.JLabel lbleditarnome;
    private javax.swing.JTextField txteditarnome;
    // End of variables declaration//GEN-END:variables
}
