/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;


import br.com.ifba.curso.controller.CursoController;
import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class TelaListar extends javax.swing.JFrame {
    private final CursoIController cursoController = new CursoController();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaListar.class.getName());

    /**
     * Creates new form CursoListar
     */
    public TelaListar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpesquisar = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblresultados = new javax.swing.JTable();
        btnvoltarlistar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblpesquisar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpesquisar.setText("PESQUISAR");
        getContentPane().add(lblpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 20));
        getContentPane().add(txtpesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 210, -1));

        btnbuscar.setText("BUSCAR");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        tblresultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Codigo ", "Nome", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblresultados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 170));

        btnvoltarlistar.setText("VOLTAR");
        btnvoltarlistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvoltarlistarActionPerformed(evt);
            }
        });
        getContentPane().add(btnvoltarlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        try{
            Long id = Long.valueOf(txtpesquisar.getText());
           
            Curso c = cursoController.findById(id);
            
            DefaultTableModel model = (DefaultTableModel) tblresultados.getModel();
            model.setRowCount(0);
            
            if(c != null){
                model.addRow(new Object[]{
                    c.getId(),
                    c.getCodigocurso(),
                    c.getNome(),
                    c.isAtivo() ? "Ativo" : "Inativo"
                });
            }else {
                JOptionPane.showMessageDialog(this, "Nenhum curso encontrado com esse ID");
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "ID inválido");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao buscar curso: " + e.getMessage());
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnvoltarlistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvoltarlistarActionPerformed
        // TODO add your handling code here:
        TelaInicial telainicial = new TelaInicial();
        telainicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvoltarlistarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnvoltarlistar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblpesquisar;
    private javax.swing.JTable tblresultados;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
